dataset:
  name: "alpaca"
  type: "instruction"  # Options: instruction, chat, completion
  source:
    type: "huggingface"  # Options: huggingface, s3, local
    path: "tatsu-lab/alpaca"
    split: "train"
  
  preprocessing:
    max_length: 512
    text_column: "text"
    prompt_template: |
      Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
      
      ### Instruction:
      {instruction}
      
      ### Input:
      {input}
      
      ### Response:
      {output}
    
  validation:
    validation_split: 0.1
    validation_strategy: "random"  # Options: random, time-based, custom
    
  data_collator:
    type: "default"  # Options: default, custom
    pad_to_multiple_of: 8
    
storage:
  input_path: "/fsx/datasets/alpaca"
  output_path: "/fsx/datasets/alpaca_processed"
  checkpoint_path: "/fsx/checkpoints/alpaca" 